services:
  - type: redis
    name: celery-redis
    region: ohio
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
  - type: worker
    name: queue
    region: ohio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A tasks worker -l info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: web
    name: flower
    region: ohio
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A tasks beat -l info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString

